{% set name = "attributedict" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/attributedict-{{ version }}.tar.gz
  sha256: 983c3ab52ca1817785a3cd22f7d975ead4b1cbe7bc466c5ec1d4728eae791c7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-git >=1.2
    - pip
  run:
    - python >=3.8
    - rootpath >=0.1.0
    - inspecta >=0.1.0
    - colour-runner >=0.0.5
    - deepdiff >=3.3.0
    - tox >=3.0.0
    - coverage >=4.5.2
    - codecov >=2.0.15

test:
  imports:
    - attributedict
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/grimen/python-attributedict
  summary: A dictionary object with attributes support.
  license: MIT
  license_file: MIT-LICENSE

extra:
  recipe-maintainers:
    - mediocretech
